# Generated by Django 4.2 on 2023-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_testapiview_testapi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testapi',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testapi',
            name='extra_name',
            field=models.CharField(default='null', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='testapi',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
