# Generated by Django 4.2 on 2023-04-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_testapi_options_testapi_extra_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testapi',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Test Api Table'},
        ),
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.timestamp')),
                ('milage', models.FloatField(blank=True, null=True)),
                ('test_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='test_app.testapi')),
            ],
            options={
                'verbose_name_plural': 'ModelX',
                'ordering': ['-created_at'],
            },
            bases=('test_app.timestamp',),
        ),
    ]
