# Generated by Django 4.2 on 2023-04-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_testapi_options_modelx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelx',
            name='test_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_x', to='test_app.testapi'),
        ),
        migrations.CreateModel(
            name='ModelY',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.timestamp')),
                ('milage', models.FloatField(blank=True, null=True)),
                ('test_content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_y', to='test_app.testapi')),
            ],
            options={
                'verbose_name_plural': 'ModelY',
                'ordering': ['-created_at'],
            },
            bases=('test_app.timestamp',),
        ),
    ]
